In [0]:
import numpy as np

Q1. **Get the positions where elements of a and b match**

Input:

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

Output:

(array([1, 3, 5, 7]),)



In [0]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [0]:
# Write code for Q1 here
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.where(a == b)


(array([1, 3, 5, 7]),)

Q2. **Get all items between 5 and 10 from a.**

a = np.array([2, 6, 1, 9, 10, 3, 27])

In [0]:
# Write code for Q2 here
a = np.array([2, 6, 1, 9, 10, 3, 27])
a[np.where((a >= 5) & (a <=10))]

array([ 6,  9, 10])

Q3. **Swap columns 1 and 2 in the array arr.**

arr = np.arange(9).reshape(3,3)

In [0]:
# Write code for Q3 here
arr = np.arange(9).reshape(3,3)
arr
arr[:,[1,2]]=arr[:,[2,1]]
arr

array([[0, 2, 1],
       [3, 5, 4],
       [6, 8, 7]])

Q4. Reverse the rows of a 2D array arr.

arr = np.arange(9).reshape(3,3)

In [0]:
# Write code for Q4 here
arr = np.arange(9).reshape(3,3)
reversedArr = np.flip(arr, axis=0)
 
print(arr)
print('Reversed Array')
print(reversedArr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
Reversed Array
[[6 7 8]
 [3 4 5]
 [0 1 2]]


Q5. Find the 5th and 95th percentile of iris's sepallength
Note - Find input code in the next cell

In [0]:
import numpy as np
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])
print(sepallength)

# Write code for Q5 here
print(np.percentile(sepallength,5))
print(np.percentile(sepallength,95))

[5.1 4.9 4.7 4.6 5.  5.4 4.6 5.  4.4 4.9 5.4 4.8 4.8 4.3 5.8 5.7 5.4 5.1
 5.7 5.1 5.4 5.1 4.6 5.1 4.8 5.  5.  5.2 5.2 4.7 4.8 5.4 5.2 5.5 4.9 5.
 5.5 4.9 4.4 5.1 5.  4.5 4.4 5.  5.1 4.8 5.1 4.6 5.3 5.  7.  6.4 6.9 5.5
 6.5 5.7 6.3 4.9 6.6 5.2 5.  5.9 6.  6.1 5.6 6.7 5.6 5.8 6.2 5.6 5.9 6.1
 6.3 6.1 6.4 6.6 6.8 6.7 6.  5.7 5.5 5.5 5.8 6.  5.4 6.  6.7 6.3 5.6 5.5
 5.5 6.1 5.8 5.  5.6 5.7 5.7 6.2 5.1 5.7 6.3 5.8 7.1 6.3 6.5 7.6 4.9 7.3
 6.7 7.2 6.5 6.4 6.8 5.7 5.8 6.4 6.5 7.7 7.7 6.  6.9 5.6 7.7 6.3 6.7 7.2
 6.2 6.1 6.4 7.2 7.4 7.9 6.4 6.3 6.1 7.7 6.3 6.4 6.  6.9 6.7 6.9 5.8 6.8
 6.7 6.7 6.3 6.5 6.2 5.9]
4.6
7.254999999999998


Q6. Find the positions of NaN in the sepalLength numpy array

In [0]:
# This is the input of your question
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float')
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

sepalLength=iris_2d[:,0]
# This is the sepalLength
print(sepalLength)

# Write your code here
# Hint - You can use the isNan() function.
print('The Answer')
np.isnan(sepalLength).nonzero()


[5.1 4.9 4.7 4.6 5.  5.4 nan 5.  4.4 4.9 5.4 4.8 4.8 nan 5.8 5.7 5.4 5.1
 5.7 5.1 5.4 5.1 4.6 5.1 4.8 5.  5.  5.2 5.2 4.7 4.8 5.4 5.2 5.5 4.9 5.
 5.5 4.9 4.4 nan 5.  4.5 4.4 5.  5.1 4.8 5.1 4.6 5.3 5.  7.  6.4 6.9 5.5
 6.5 5.7 6.3 4.9 6.6 5.2 5.  5.9 6.  6.1 5.6 6.7 5.6 5.8 6.2 5.6 5.9 6.1
 6.3 6.1 6.4 6.6 6.8 6.7 6.  5.7 5.5 5.5 5.8 6.  5.4 6.  6.7 6.3 5.6 5.5
 5.5 6.1 5.8 5.  5.6 5.7 5.7 6.2 5.1 5.7 nan 5.8 7.1 6.3 6.5 7.6 4.9 nan
 6.7 7.2 6.5 6.4 6.8 5.7 5.8 6.4 6.5 7.7 7.7 6.  6.9 5.6 7.7 6.3 6.7 7.2
 6.2 6.1 6.4 7.2 7.4 7.9 6.4 6.3 6.1 7.7 6.3 6.4 6.  6.9 6.7 6.9 5.8 6.8
 6.7 6.7 nan 6.5 6.2 5.9]
The Answer


(array([  6,  13,  39, 100, 107, 146]),)

Q7 .Replace all the null values with 0 in the above used sepalLength array

In [0]:
# Write your code here
np.nan_to_num(sepalLength,0)

array([5.1, 4.9, 4.7, 4.6, 5. , 5.4, 0. , 5. , 4.4, 4.9, 5.4, 4.8, 4.8,
       0. , 5.8, 5.7, 5.4, 5.1, 5.7, 5.1, 5.4, 5.1, 4.6, 5.1, 4.8, 5. ,
       5. , 5.2, 5.2, 4.7, 4.8, 5.4, 5.2, 5.5, 4.9, 5. , 5.5, 4.9, 4.4,
       0. , 5. , 4.5, 4.4, 5. , 5.1, 4.8, 5.1, 4.6, 5.3, 5. , 7. , 6.4,
       6.9, 5.5, 6.5, 5.7, 6.3, 4.9, 6.6, 5.2, 5. , 5.9, 6. , 6.1, 5.6,
       6.7, 5.6, 5.8, 6.2, 5.6, 5.9, 6.1, 6.3, 6.1, 6.4, 6.6, 6.8, 6.7,
       6. , 5.7, 5.5, 5.5, 5.8, 6. , 5.4, 6. , 6.7, 6.3, 5.6, 5.5, 5.5,
       6.1, 5.8, 5. , 5.6, 5.7, 5.7, 6.2, 5.1, 5.7, 0. , 5.8, 7.1, 6.3,
       6.5, 7.6, 4.9, 0. , 6.7, 7.2, 6.5, 6.4, 6.8, 5.7, 5.8, 6.4, 6.5,
       7.7, 7.7, 6. , 6.9, 5.6, 7.7, 6.3, 6.7, 7.2, 6.2, 6.1, 6.4, 7.2,
       7.4, 7.9, 6.4, 6.3, 6.1, 7.7, 6.3, 6.4, 6. , 6.9, 6.7, 6.9, 5.8,
       6.8, 6.7, 6.7, 0. , 6.5, 6.2, 5.9])

Q8. Find the 2nd largest value for the given array.

In [0]:
# Input
arr=np.random.randint(23,78, size=9).reshape(3,3)
print(arr)
arr1=np.ravel(arr)
arr1.sort
print('2nd largest value')
arr1[-2]

# Write your code here

[[47 52 63]
 [25 40 45]
 [40 61 36]]
2nd largest value


61

Q9. From the array a, replace all values greater than 30 by 30 and less than 10 by 10.

In [0]:
# Input
arr=np.random.randint(1,78, size=9).reshape(3,3)
arr

# Write your code here
arr[arr>30]=30
arr[arr<10]=10
arr

array([[11, 30, 30],
       [30, 10, 30],
       [30, 30, 23]])

Q10. Drop all nan values from a 1D numpy array

In [0]:
arr=np.array([1,2,3,np.nan,5,6,7,np.nan])
arr
# Write code here
np.argwhere(np.isnan(arr))
cleararr=np.delete(arr,np.argwhere(np.isnan(arr)))
cleararr

array([1., 2., 3., 5., 6., 7.])